[package]
name = "main"
version = "0.1.0"
authors = ["Nouzan <clobraindie@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lesson-linear = { path = "../lesson-linear" }
actix-web = "1.0"